#!/usr/bin/env python3
import re
import sys

if len(sys.argv) != 2:
    print(f'usage: {sys.argv[0]} <command>', file = sys.stderr)
    exit(1)

#read the data from stdin
#output = []
def quit_num(n):
    cnt = 0
    while 1:
        try:
            cont = input()
            if cnt < n:
                print(cont)
                cnt +=1 
            else:
                break;
        
        except EOFError as e:
            break

def quit_reg(exp):
    ret = []
    # pat = re.compile(rf'{exp}')
    # for l in lines:
    #     ret.append(l)
    #     if(re.match(pat, l)): 
    #         break
    return ret

def quit(cmd):
    ret = []
    if len(cmd) == 1:
        num = int(cmd[0][:-1])
        quit_num(num)
    else:
        exp = cmd[1]
        
    



#process the command

cmd_list = sys.argv[1].split('/')

#In subset 0, this address can either be a line number or a regex.
# quit command
if sys.argv[1][-1] == 'q':
    quit(cmd_list)








#print(cmd_list)
