#!/usr/bin/env python3
import re
import sys
from tkinter.tix import InputOnly
n = 20
cnt = 0

while 1:
    try:
        #cont = sys.stdin.readline()
        cont = input()
        if cnt < n:
            print(cont)
            cnt +=1 
        else:
            break;
        
    except EOFError as e:
        print("eof")
        break





    


