#!/bin/dash
2041 autotest slippy test55_subset1_substitute slippy
2041 autotest slippy test56_subset1_substitute slippy
2041 autotest slippy test57_subset1_substitute slippy
2041 autotest slippy test58_subset1_substitute slippy