#!/bin/dash
2041 autotest slippy test27_subset0_delete slippy
2041 autotest slippy test28_subset0_delete slippy
2041 autotest slippy test29_subset0_delete slippy
2041 autotest slippy test30_subset0_delete slippy
2041 autotest slippy test31_subset0_delete slippy
2041 autotest slippy test32_subset0_delete slippy
2041 autotest slippy test33_subset0_delete slippy