#!/bin/dash
2041 autotest slippy test1_subset0_quit slippy
2041 autotest slippy test2_subset0_quit slippy
2041 autotest slippy test3_subset0_quit slippy
2041 autotest slippy test4_subset0_quit slippy
2041 autotest slippy test5_subset0_quit slippy
2041 autotest slippy test6_subset0_quit slippy
2041 autotest slippy test7_subset0_quit slippy
2041 autotest slippy test8_subset0_quit slippy
2041 autotest slippy test9_subset0_quit slippy
2041 autotest slippy test10_subset0_quit slippy
2041 autotest slippy test11_subset0_quit slippy
2041 autotest slippy test12_subset0_quit slippy
2041 autotest slippy test13_subset0_quit slippy
2041 autotest slippy test14_subset0_quit slippy
