#!/bin/dash

if [ -d ".tigger" ]
then
	echo "tigger-init: error: .tigger already exists"
	exit 1
fi

mkdir ".tigger"
echo "Initialized empty tigger repository in .tigger"

mkdir ".tigger"/"index"
mkdir ".tigger"/"cache"
mkdir ".tigger"/"status"
