#!/bin/dash

if test "$#" -gt 0 
then
	echo "usage: tigger-init"
	exit 1
fi

if test -d ".tigger"
then
	echo "tigger-init: error: .tigger already exists"
	exit 1
fi

mkdir ".tigger"
echo "Initialized empty tigger repository in .tigger"

mkdir ".tigger"/"index"
mkdir ".tigger"/"cache"
mkdir ".tigger"/"status"
